<script lang="ts">
  import { onMount } from 'svelte'; import { api } from '@/api/client'; import type { HealthResponse } from '@/api/types'; import { ui } from '@/lib/state/ui.svelte'; import { go } from '@/lib/router.svelte'
  let status=$state<Record<string,any>>({}); let doctor=$state<Record<string,any>>({}); let projects=$state<any[]>([]); let busy=$state(false); let error=$state('')
  const h=$derived((ui.health??{}) as HealthResponse); const checks=$derived((doctor.checks??doctor.items??[]) as any[])
  async function load(){busy=true;error='';try{const [s,d,p]=await Promise.all([api.get<any>('/v1/status'),api.get<any>('/v1/doctor'),api.get<any>('/v1/projects')]);status=s;doctor=d;projects=p.items??[]}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=false}}
  async function checkpoint(){try{await api.post('/v1/operations/checkpoint');ui.toast('Checkpoint завершён','ok');await load()}catch(e){ui.toast(String(e),'error')}}
  onMount(load)
  const metrics=$derived([{label:'Документы',value:h.documents??status.documents??'—',sub:`${projects.length} проектов`,color:'l0'},{label:'Чанки',value:h.chunks??status.chunks??'—',sub:'поисковый корпус',color:'l1'},{label:'Узлы графа',value:h.nodes??status.nodes??'—',sub:`${h.edges??status.edges??'—'} рёбер`,color:'l2'},{label:'Вики',value:status.wiki_documents??'—',sub:'скомпилированные знания',color:'l3'},{label:'Состояние',value:h.ok?'OK':'—',sub:h.ok?'gateway доступен':'ожидание ответа',color:'l4'}])
</script>
<div class="screen"><div class="screen-head"><div><h1>Пульт</h1><p>Состояние корпуса, retrieval, графа и фоновых операций</p></div><div class="actions"><button class="secondary" onclick={load} disabled={busy}>doctor</button><button class="primary" onclick={checkpoint}>checkpoint</button></div></div>
{#if error}<div class="error">{error}</div>{/if}
<section class="metrics">{#each metrics as m}<article class="metric {m.color}"><span>{m.label}</span><strong>{m.value}</strong><small>{m.sub}</small></article>{/each}</section>
<section class="grid"><article class="panel health"><div class="panel-title"><span>Здоровье слоёв</span><em>{checks.length||5} проверок</em></div><div class="layers">{#each ['Корпус · L0','Retrieval · L1','Граф · L2','Вики · L3','Агенты · L4'] as layer,i}<button onclick={()=>go((['corpus','search','graph','wiki','agents'] as const)[i])}><i class="c{i}"></i><span><b>{layer}</b><small>{checks[i]?.message??(h.ok?'готов':'нет данных')}</small></span><strong>{checks[i]?.ok===false?'!':'✓'}</strong></button>{/each}</div></article>
<article class="panel projects"><div class="panel-title"><span>Проекты</span><em>{projects.length}</em></div>{#if projects.length}{#each projects.slice(0,8) as p}<div class="project"><span><b>{p.project_id??p.name??p.project??p.id??'project'}</b><small>{p.rooms?.length?`${p.rooms.length} комнат`:(p.root??p.path??p.wing??'изолированный scope')}</small></span><strong>{p.documents??p.document_count??'·'}</strong></div>{/each}{:else}<div class="empty">Проекты появятся после ответа gateway</div>{/if}</article>
<article class="panel runtime"><div class="panel-title">Контур выполнения</div><div class="flow"><span>sources</span><i>→</i><span class="l0">documents</span><i>→</i><span class="l1">chunks + FTS</span><i>→</i><span class="l2">graph</span><i>→</i><span class="l3">wiki</span></div><pre>{JSON.stringify(status.runtime??status.storage??{writer:'gateway',database:h.db_path??'—'},null,2)}</pre></article></section></div>
<style>
 .actions{display:flex;gap:8px}.metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;margin-bottom:14px}.metric{position:relative;overflow:hidden;background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:13px 14px}.metric:before{content:'';position:absolute;left:0;right:0;top:0;height:2px;background:var(--layer)}.metric span{display:block;text-transform:uppercase;letter-spacing:.07em;color:var(--text-muted);font-size:10px;font-weight:700}.metric strong{display:block;font-size:25px;margin:6px 0 2px;letter-spacing:-.04em}.metric small{color:var(--text-faint);font:10px var(--mono)}.l0{--layer:var(--l0)}.l1{--layer:var(--l1)}.l2{--layer:var(--l2)}.l3{--layer:var(--l3)}.l4{--layer:var(--l4)}.grid{display:grid;grid-template-columns:1.2fr .8fr;gap:14px}.panel-title{display:flex;justify-content:space-between}.panel-title em{font:10px var(--mono);color:var(--text-faint);font-style:normal}.layers button{width:100%;height:55px;border:0;border-bottom:1px solid var(--border);background:transparent;color:var(--text);display:flex;align-items:center;gap:11px;padding:0 14px;text-align:left;cursor:pointer}.layers button:hover{background:var(--bg-hover)}.layers i{width:8px;height:8px;border-radius:50%;background:var(--l0)}.layers i.c1{background:var(--l1)}.layers i.c2{background:var(--l2)}.layers i.c3{background:var(--l3)}.layers i.c4{background:var(--l4)}.layers span{display:flex;flex-direction:column;flex:1}.layers small,.project small{color:var(--text-faint);font-size:10px;margin-top:3px}.layers strong{color:var(--ok)}.project{min-height:55px;padding:9px 14px;border-bottom:1px solid var(--border);display:flex;align-items:center;justify-content:space-between}.project span{display:flex;flex-direction:column}.project strong{font:12px var(--mono);color:var(--text-muted)}.runtime{grid-column:1/3;padding-bottom:12px}.flow{display:flex;align-items:center;gap:8px;padding:14px}.flow span{border:1px solid var(--border);border-top:2px solid var(--layer,var(--text-faint));border-radius:7px;padding:7px 10px;font:11px var(--mono)}.flow i{color:var(--text-faint)}pre{margin:0 14px;padding:10px;background:#090b10;border-radius:8px;color:var(--text-muted);font:10px/1.5 var(--mono);max-height:100px;overflow:auto}.error{padding:10px;color:var(--danger)}.empty{padding:30px;color:var(--text-faint);text-align:center}@media(max-width:1050px){.metrics{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}.runtime{grid-column:auto}}
</style>
