<script lang="ts">
 import {onMount} from 'svelte'; import {api} from '@/api/client'; import {goWiki} from '@/lib/router.svelte'
 let rows=$state<any[]>([]),total=$state(0),q=$state(''),kind=$state('all'),busy=$state(false),error=$state('')
 const filtered=$derived(rows.filter(r=>(kind==='all'||r.kind===kind)&&`${r.title??''} ${r.uri??''} ${r.wing??''}`.toLowerCase().includes(q.toLowerCase())))
 async function load(){busy=true;error='';try{const d=await api.get<any>('/v1/documents?limit=200');rows=d.items??d.documents??[];total=d.page?.total??d.total??rows.length}catch(e){error=String(e)}finally{busy=false}} onMount(load)
</script>
<div class="screen"><div class="screen-head"><div><h1>Корпус</h1><p>{total} документов · первичный слой знаний L0</p></div><button class="secondary" onclick={load}>Обновить</button></div><div class="toolbar"><input bind:value={q} placeholder="Фильтр по названию, URI или проекту…"><div>{#each ['all','raw','wiki','diary'] as k}<button class:active={kind===k} onclick={()=>kind=k}>{k}</button>{/each}</div></div>
<div class="table panel"><div class="thead"><span>Документ</span><span>Тип</span><span>Проект / комната</span><span>Обновлён</span></div>{#if error}<div class="empty error">{error}</div>{:else if busy}<div class="empty">Загрузка корпуса…</div>{:else if !filtered.length}<div class="empty">Ничего не найдено</div>{:else}{#each filtered as row}<button class="tr" onclick={()=>row.id&&goWiki(row.id)}><span><b>{row.title??row.uri??row.id}</b><small>{row.uri??row.source_file??row.id}</small></span><span><i class="kind">{row.kind??row.layer??'doc'}</i></span><span>{[row.wing,row.room].filter(Boolean).join(' / ')||'без проекта'}</span><span class="mono">{(row.updated_at??'—').slice?.(0,16)??'—'}</span></button>{/each}{/if}</div></div>
<style>.toolbar{display:flex;justify-content:space-between;gap:12px;margin-bottom:12px}.toolbar input{width:min(520px,60%);height:34px;border:1px solid var(--border);border-radius:8px;background:var(--surface);padding:0 11px}.toolbar div{display:flex;border:1px solid var(--border);border-radius:8px;overflow:hidden}.toolbar button{border:0;border-left:1px solid var(--border);background:var(--surface);color:var(--text-muted);padding:0 11px;cursor:pointer}.toolbar button.active{background:var(--accent-soft);color:var(--accent)}.table{overflow:hidden}.thead,.tr{display:grid;grid-template-columns:minmax(260px,2fr) 100px minmax(150px,1fr) 145px;align-items:center;gap:12px;padding:0 14px}.thead{height:38px;color:var(--text-faint);font-size:10px;text-transform:uppercase;letter-spacing:.06em;border-bottom:1px solid var(--border)}.tr{width:100%;min-height:55px;border:0;border-bottom:1px solid var(--border);background:transparent;color:var(--text-muted);text-align:left;cursor:pointer}.tr:hover{background:var(--bg-hover)}.tr>span:first-child{display:flex;flex-direction:column;min-width:0}.tr b{color:var(--text);font-size:12px}.tr small{font:10px var(--mono);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:3px}.kind{font:10px var(--mono);font-style:normal;color:var(--l0);background:color-mix(in srgb,var(--l0) 12%,transparent);padding:3px 6px;border-radius:5px}.empty{padding:60px;text-align:center;color:var(--text-faint)}.error{color:var(--danger)}</style>
