<script lang="ts">
 import {onMount} from 'svelte'; import {api} from '@/api/client'; import {ui} from '@/lib/state/ui.svelte'; import type {RouteName} from '@/lib/router.svelte'
 let {kind}:{kind:RouteName}=$props(); let primary=$state<any>({}),secondary=$state<any>({}),busy=$state(false),error=$state('')
 const config:Record<string,{title:string;subtitle:string,a:string,b:string,accent:string}>={agents:{title:'Агенты · Журнал',subtitle:'Операции, вызовы и активные исполнители',a:'/v1/agents',b:'/v1/ops-log?limit=100',accent:'var(--l4)'},evaluation:{title:'Оценка retrieval',subtitle:'История прогонов и качество поиска',a:'/v1/eval/history?limit=100',b:'/v1/lint-wiki',accent:'var(--l1)'},models:{title:'Модели и пайплайн',subtitle:'LLM, эмбеддинги и фактическая конфигурация',a:'/v1/llm-status',b:'/v1/embedding-manifest',accent:'var(--l3)'}}
 const cfg=$derived(config[kind]??config.agents); const items=$derived((secondary.items??secondary.entries??secondary.history??[]) as any[])
 async function load(){busy=true;error='';try{[primary,secondary]=await Promise.all([api.get<any>(cfg.a),api.get<any>(cfg.b)])}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=false}} $effect(()=>{kind;void load()}); onMount(load)
 function summary(v:any){if(v==null)return '—';if(typeof v==='object')return JSON.stringify(v);return String(v)}
</script>
<div class="screen" style={`--page-accent:${cfg.accent}`}><div class="screen-head"><div><h1>{cfg.title}</h1><p>{cfg.subtitle}</p></div><button class="secondary" onclick={load}>Обновить</button></div>{#if error}<div class="notice">{error}</div>{/if}<div class="layout"><section class="panel summary"><div class="panel-title">Текущее состояние</div><div class="kv">{#each Object.entries(primary).filter(([k])=>!['ok','items'].includes(k)).slice(0,12) as [key,value]}<div><span>{key.replaceAll('_',' ')}</span><strong>{summary(value)}</strong></div>{/each}{#if busy}<div><span>status</span><strong>загрузка…</strong></div>{/if}</div></section><section class="panel feed"><div class="panel-title"><span>{kind==='agents'?'Журнал операций':kind==='evaluation'?'Последние прогоны':'Манифест эмбеддингов'}</span><em>{items.length||Object.keys(secondary).length}</em></div>{#if items.length}{#each items.slice(0,40) as item}<article><i></i><div><b>{item.action??item.name??item.query??item.id??'запись'}</b><p>{item.message??item.result??item.status??item.summary??summary(item)}</p></div><time>{(item.created_at??item.timestamp??item.updated_at??'').slice?.(0,19)}</time></article>{/each}{:else}<pre>{JSON.stringify(secondary,null,2)}</pre>{/if}</section></div></div>
<style>.screen{background:radial-gradient(800px 400px at 18% -10%,color-mix(in srgb,var(--page-accent) 10%,transparent),transparent 65%),var(--bg)}.layout{display:grid;grid-template-columns:minmax(300px,.75fr) minmax(480px,1.25fr);gap:14px}.panel-title{display:flex;justify-content:space-between}.panel-title em{font:10px var(--mono);color:var(--text-faint);font-style:normal}.kv{padding:4px 14px 12px}.kv>div{display:grid;grid-template-columns:135px 1fr;gap:12px;padding:9px 0;border-bottom:1px solid var(--border)}.kv span{color:var(--text-faint);font-size:11px}.kv strong{font:500 10px/1.45 var(--mono);word-break:break-word}.feed{overflow:hidden}.feed article{display:grid;grid-template-columns:8px 1fr auto;gap:11px;padding:11px 14px;border-bottom:1px solid var(--border);align-items:start}.feed article i{width:7px;height:7px;margin-top:4px;border-radius:50%;background:var(--page-accent)}.feed b{font-size:12px}.feed p{margin:3px 0 0;color:var(--text-muted);font:10px/1.45 var(--mono);max-width:680px;overflow:hidden;text-overflow:ellipsis}.feed time{font:10px var(--mono);color:var(--text-faint)}pre{margin:0;padding:14px;font:10px/1.55 var(--mono);color:var(--text-muted);overflow:auto;max-height:620px}.notice{margin-bottom:12px;padding:10px;border:1px solid color-mix(in srgb,var(--danger) 35%,transparent);border-radius:8px;color:var(--danger);font-size:12px}@media(max-width:1000px){.layout{grid-template-columns:1fr}}</style>
