<script lang="ts">
  import { ui } from '@/lib/state/ui.svelte'; import { route } from '@/lib/router.svelte'
  const labels: Record<string,[string,string]>={console:['Пульт','L0–L4 · обзор'],corpus:['Корпус','L0 · документы'],search:['Поиск','L1 · retrieval'],graph:['Граф','L2 · связи'],wiki:['Вики','L3 · знания'],agents:['Агенты','L4 · журнал'],evaluation:['Оценка','retrieval quality'],models:['Модели','pipeline']}
  const current=$derived(labels[route.name]??labels.console)
</script>
<header class="top"><div class="crumb"><span>rag-mcp</span><i>/</i><strong>{current[0]}</strong><b>{current[1]}</b></div><button class="command" onclick={()=>ui.openCommand()}><span>Страница, документ, узел или команда…</span><kbd>⌘K</kbd></button><div class="right"><span class:bad={!!ui.healthError} class:ok={ui.health?.ok} class="health"><i></i>{ui.healthError?'offline':ui.health?`127.0.0.1:7432 · ${ui.health.documents??0} docs`:'connecting…'}</span><button onclick={()=>ui.toggleLocale()}>{ui.localeLabel}</button><button onclick={()=>ui.setTheme(ui.theme==='dark'?'light':'dark')}>{ui.theme==='dark'?'☾':'☀'}</button></div></header>
<style>
  .top{height:48px;flex:0 0 48px;display:grid;grid-template-columns:minmax(250px,1fr) minmax(280px,460px) minmax(250px,1fr);align-items:center;padding:0 16px;border-bottom:1px solid var(--border);background:var(--bg);gap:18px}.crumb{display:flex;align-items:center;gap:9px;white-space:nowrap}.crumb span,.crumb i{color:var(--text-faint);font-style:normal}.crumb b{font:500 10px var(--mono);background:var(--bg-active);color:var(--accent);padding:3px 7px;border-radius:5px}.crumb strong{font-size:13px}.command{height:30px;display:flex;align-items:center;justify-content:space-between;border:1px solid var(--border);border-radius:8px;background:var(--surface);color:var(--text-faint);padding:0 10px;cursor:pointer}.command:hover{border-color:var(--border-strong);color:var(--text-muted)}.right{display:flex;align-items:center;justify-content:flex-end;gap:8px}.right button{height:28px;min-width:30px;border:1px solid var(--border);border-radius:7px;background:transparent;color:var(--text-muted);font:600 10px var(--mono);cursor:pointer}.health{display:flex;align-items:center;gap:6px;font:500 10px var(--mono);color:var(--text-muted);white-space:nowrap}.health i{width:7px;height:7px;border-radius:50%;background:var(--warn)}.health.ok i{background:var(--ok);box-shadow:0 0 7px var(--ok)}.health.bad i{background:var(--danger)}@media(max-width:950px){.top{grid-template-columns:1fr auto}.command{display:none}.health{font-size:0}.health i{display:block}}
</style>
